"""empty message

Revision ID: b3632724fdbe
Revises: b9c94085c72b
Create Date: 2022-08-15 22:02:46.876060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3632724fdbe'
down_revision = 'b9c94085c72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CLIENT_ID', postgresql.UUID(), nullable=True),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.Column('USERNAME', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['CLIENT_ID'], ['CLIENT.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CLIENT_ID', 'USERNAME', name='_client_username_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USER')
    # ### end Alembic commands ###
