"""empty message

Revision ID: 421324a9b087
Revises: 66aeec8bec60
Create Date: 2022-08-10 00:50:41.937767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '421324a9b087'
down_revision = '66aeec8bec60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOKEN', sa.Column('client_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'TOKEN', 'CLIENT', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TOKEN', type_='foreignkey')
    op.drop_column('TOKEN', 'client_id')
    # ### end Alembic commands ###
