"""empty message

Revision ID: f799538f2120
Revises: dc9e2cc3ae96
Create Date: 2022-08-09 22:49:27.887279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f799538f2120'
down_revision = 'dc9e2cc3ae96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CLIENT', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('CLIENT', sa.Column('modified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CLIENT', 'modified')
    op.drop_column('CLIENT', 'created')
    # ### end Alembic commands ###
